### ISSUE TITLE
The searchAnime class doesnot work.

### ISSUE THREAD

**Issue by BibhuLamichhane** [anilistpy/anilistpy#1]
The documentation needs to be updated

**Comment by 0kalekale** [comment]
thank you for pointing this out!
instead of updating the documenation i have made changes that would fit the doucmenation. 
[this](https://github.com/anilistpy/anilistpy/commit/e7a6f8138bc763ac4ba591196de5096cd222559b) fixes this issue.

example use case:
```py
>>> import anilistpy
>>> result = anilistpy.animeSearch("naruto")
>>> result.title(0)
'Naruto'
```
